services:

  apache:
    build: .docker/apache
    container_name: "infopoint-energy_apache"
    ports:
    - '80:80'
    - '443:443'
    volumes:
    - .docker/config/vhosts:/etc/apache2/sites-enabled
    - .:/home/wwwroot/infopoint-energy
    networks:
    - infopoint-energy
    depends_on:
    - php

  mysql:
    image: mariadb:10.3.32
    container_name: "infopoint-energy_mysql"
    command: --max_allowed_packet=1073741824
    ports:
    - '3306:3306'
    volumes:
    - mysql-data:/var/lib/mysql
    networks:
    - infopoint-energy
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: "infopoint-energy"
      MYSQL_USER: "infopoint-energy"
      MYSQL_PASSWORD: "infopoint-energy"

  php:
    build: .docker/php
    container_name: "infopoint-energy_php"
    volumes:
    - .:/home/wwwroot/infopoint-energy
    - php-var:/home/wwwroot/infopoint-energy/var
    environment:
    - "maildev_host=infopoint-energy_maildev"
    networks:
    - infopoint-energy
    depends_on:
    - maildev
    - mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: "infopoint-energy_phpmyadmin"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      UPLOAD_LIMIT: 30000000000
    networks:
    - infopoint-energy
    ports:
    - '8080:80'
    links:
    - mysql

  maildev:
    image: djfarrelly/maildev
    container_name: "infopoint-energy_maildev"
    command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
    networks:
    - infopoint-energy
    ports:
    - '8001:80'
    - '25:25'

networks:
  infopoint-energy:
    driver: bridge

volumes:
  mysql-data:
    driver: local
  php-var:
    driver: local